config/routes.rb
Restbook::Engine.routes.draw do
  resources :comments, except: ["edit", "update", "destroy"] # eventually...
  
  root to: "comments#index"
  match "sign" => "comments#new"
end

app/models/restbook/comment.rb
module Restbook
  class Comment < ActiveRecord::Base
    attr_accessible :author, :body
    
    validates :author, presence: true, length: { maximum: 80 }
    validates :body, presence: true, length: { maximum: 1000 }
  end
end

app/controllers/restbook/application_controller.rb
module Restbook
  # Inherit from the App Controller of the application we are mounted inside
  # of, so that its layout can be used.
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/restbook/comments_controller.rb
module Restbook
  class CommentsController < ApplicationController
    def index
      respond_to do |format|
        format.html { @comments = Comment.find(:all, order: "created_at desc") }
        format.json do
          # preserve insertion order for JSON.
          @comments = Comment.find(:all)
          render :json => @comments
        end
      end
    end
    
    def new
      @comment = Comment.new
    end
    
    def show
      @comment = Comment.find(params[:id])
      respond_to do |format|
        format.html
        format.json { render :json => @comment }
      end
    end
    
    def create
      @comment = Comment.new(params[:comment])
      if @comment.save
        redirect_to root_path
      else
        render :new
      end
    end
  end
end

app/helpers/restbook/application_helper.rb
module Restbook
  module ApplicationHelper
  end
end

app/helpers/restbook/comments_helper.rb
module Restbook
  module CommentsHelper
    # The Rails tutorial has a very nice wrap helper, so I'll use it too.
    def wrap(content, max_width=30)
      sanitize(raw(content.split.map{ |s| wrap_long_string(s,max_width) }.join(' ')))
    end

    private

    def wrap_long_string(text, max_width=30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
  end
end

app/views/layouts/restbook/application.html.haml
!!!
%html
%head
  %title RESTbook
  = stylesheet_link_tag  "restbook/application"
  = javascript_include_tag "restbook/application"
  = csrf_meta_tags
%body
  %header
    %h1 Welcome to RESTbook!
    %nav
      %ul
        %li= link_to "Read the RESTbook!", root_path
        %li= link_to "Sign the RESTbook!", sign_path
  %section#container
    = yield

app/views/restbook/comments/_comment.html.haml
%article.restbook-comment
  %p= comment.body
  %footer by #{comment.author}, #{link_to "#{time_ago_in_words(comment.created_at)} ago", comment}.

app/views/restbook/comments/index.html.haml
/ TODO: Insert rad-rotating-3D-envelope.gif
%h1 Signatures
= render @comments

app/views/restbook/comments/new.html.haml
= form_for @comment do |f|
  - if @comment.errors.any?
    #errorExplanation
      %h2 #{pluralize(@comment.errors.count, "error")} prevented this comment from being saved:
      %p
        %ul
          =list_of(@comment.errors.full_messages) do |msg|
            = msg
  %fieldset
    %legend Add your signature!
    = f.label :author, "Your name:"
    = f.text_field :author, placeholder: "#1 RESTbook Fan"
    = f.label :body, "Message:"
    = f.text_area :body, placeholder: "RESTbook rules!"
    = f.submit "Submit"

app/views/restbook/comments/show.html.haml
%h1 Comment
= render @comment